"""create tables

Revision ID: 502c827258bb
Revises: 
Create Date: 2023-10-27 18:01:53.311777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '502c827258bb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medical_records', sa.Column('allergies', sa.String(length=100), nullable=False))
    op.add_column('medical_records', sa.Column('pcp', sa.String(length=100), nullable=False))
    op.drop_column('medical_records', 'treatment')
    op.add_column('patients', sa.Column('insurance', sa.String(length=100), nullable=False))
    op.alter_column('patients', 'contact_number',
               existing_type=mysql.VARCHAR(length=15),
               type_=sa.String(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('patients', 'contact_number',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=15),
               existing_nullable=True)
    op.drop_column('patients', 'insurance')
    op.add_column('medical_records', sa.Column('treatment', mysql.VARCHAR(length=200), nullable=True))
    op.drop_column('medical_records', 'pcp')
    op.drop_column('medical_records', 'allergies')
    # ### end Alembic commands ###
